releaseCheck.sh: use API query and update counts for SBOM .sig file
adoptium/github-release-scripts pull request #104
Opened 2023-01-12 16:08 UTC by sxa

Release tool will not be able to do its checks in the job output without this

Signed-off-by: Stewart X Addison <sxa@redhat.com>

2023-01-13 21:48 UTC, karianna requested changes

2023-01-13 21:48 UTC, karianna commented on sbin/releaseCheck.sh
> +# rm releaseCheck.$$.tmp
Why commented out?

2023-01-13 21:48 UTC, karianna commented on sbin/releaseCheck.sh
> +      echo "Windows on $ARCH: INCOMPLETE: $ACTUAL/$EXPECTED  (Expect jre, jdk, msi-jre msi-jdk, debugimage, static-libs (Not JDK8) in base, json, sha256, GPG sig, plus 3 SBOMs"
```suggestion
      echo "Windows on $ARCH: INCOMPLETE: $ACTUAL/$EXPECTED (Expect jre, jdk, msi-jre msi-jdk, debugimage, static-libs (Not JDK8) in base, json, sha256, GPG sig, plus 3 SBOMs"
```

2023-01-16 12:10 UTC, sxa commented on sbin/releaseCheck.sh
> +      echo "Windows on $ARCH: INCOMPLETE: $ACTUAL/$EXPECTED  (Expect jre, jdk, msi-jre msi-jdk, debugimage, static-libs (Not JDK8) in base, json, sha256, GPG sig, plus 3 SBOMs"
Sorted

2023-01-16 22:39 UTC, karianna approved these changes
LGTM

2023-01-16 22:39 UTC, karianna approved these changes
LGTM

2023-02-08 08:11 UTC, gdams approved these changes

2023-02-08 08:18 UTC, merged