Devkit publish tool updates to support publishing devkit binaries to https://github.com/adoptium/devkit-binaries
adoptium/github-release-scripts pull request #152
Opened 2024-03-12 16:37 UTC by andrew-m-leonard

Test publish: https://github.com/adoptium/devkit-binaries/releases/tag/gcc-11.3.0-Centos7.6.1810-b01
Using new job: https://ci.adoptium.net/job/build-scripts/job/release/job/publish_devkit_tool/6/

2024-04-03 15:35 UTC, sxa approved these changes
Approving on the basis it has been run and seems to work.

2024-04-04 04:12 UTC, karianna requested changes

2024-04-04 04:12 UTC, karianna commented on adopt-github-release/src/main/groovy/net/adoptium/release/UploadFiles.groovy
> +          uploadFiles(release, grouped.get("adopt"))
grouped may not be definted here?

2024-04-04 09:01 UTC, karianna approved these changes

2024-04-04 09:02 UTC, merged